export const seafarerDisplayedColumns = [
  { id: 0, databaseColumnName: 'EmpId', displayedColumnName: 'EMP ID', isVisible: true },
  { id: 1, databaseColumnName: 'EmployeeName', displayedColumnName: 'Name', isVisible: true },
  { id: 2, databaseColumnName: 'Nationality', displayedColumnName: 'Nationality', isVisible: true },
  { id: 3, databaseColumnName: 'BirthDate', displayedColumnName: 'Date Of Birth', isVisible: true },
  { id: 4, databaseColumnName: 'JobName', displayedColumnName: 'Rank', isVisible: true },
  { id: 5, databaseColumnName: 'Phone', displayedColumnName: 'Phone Number', isVisible: false },
  { id: 6, databaseColumnName: 'Mobile', displayedColumnName: 'Mobile Number', isVisible: true },
  { id: 7, databaseColumnName: 'Email', displayedColumnName: 'Email', isVisible: true },
  { id: 8, databaseColumnName: 'BirthPlace', displayedColumnName: 'Place of Birth', isVisible: false },
  { id: 9, databaseColumnName: 'Age', displayedColumnName: 'Age', isVisible: true },
  { id: 10, databaseColumnName: 'Religion', displayedColumnName: 'Religion', isVisible: false },
  { id: 11, databaseColumnName: 'MaritalStatus', displayedColumnName: 'Marital Status', isVisible: false },
  { id: 12, databaseColumnName: 'EmploymentDate', displayedColumnName: 'Date of Hire', isVisible: false },
  { id: 13, databaseColumnName: 'PassportNumber', displayedColumnName: 'Passport Number', isVisible: true },
  { id: 14, databaseColumnName: 'PassPortIssueDate', displayedColumnName: 'Passport Issue Date', isVisible: false },
  { id: 15, databaseColumnName: 'PassportExpireDate', displayedColumnName: 'Passport Expiry Date', isVisible: true },
  { id: 16, databaseColumnName: 'VisaUAEIdNO', displayedColumnName: 'VISA / UAE ID NO', isVisible: false },
  { id: 17, databaseColumnName: 'VisaIssueDate', displayedColumnName: 'VISA / UAE ID ISSUE DATE', isVisible: false },
  { id: 18, databaseColumnName: 'VisaExpiryDate', displayedColumnName: 'VISA / UAE ID EXPIRY DATE', isVisible: false },
  { id: 19, databaseColumnName: 'SponsorName', displayedColumnName: 'VISA SPONSOR', isVisible: false },
  { id: 20, databaseColumnName: 'Remarks', displayedColumnName: 'Remarks', isVisible: false },
  { id: 21, databaseColumnName: 'NameOfSpouse', displayedColumnName: 'Name Of Spouse', isVisible: false },
  { id: 22, databaseColumnName: 'NoOfChildren', displayedColumnName: 'No Of Children', isVisible: false },
  { id: 23, databaseColumnName: 'BodyWeight', displayedColumnName: 'Body Weight (Kg)', isVisible: false },
  { id: 24, databaseColumnName: 'Height', displayedColumnName: 'Height (in cm)', isVisible: false },
  { id: 25, databaseColumnName: 'NearestAirport', displayedColumnName: 'Nearest Airport', isVisible: false },
  { id: 26, databaseColumnName: 'ResidenceNumber', displayedColumnName: 'Residence Number', isVisible: false },
  { id: 27, databaseColumnName: 'InsuranceDate', displayedColumnName: 'Health Insurance Expiry Date', isVisible: false },
  { id: 28, databaseColumnName: 'actions', displayedColumnName: 'Actions', isVisible: true }
];
